name: Update README Activity

on:
  schedule:
    - cron: "0 0 * * *"   # runs once daily at midnight UTC
  workflow_dispatch:        # lets you trigger it manually too

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
